### ISSUE TITLE
Orientation bugs

### ISSUE THREAD

**Issue by bobbyali** [bobbyali/kidzvids2#1]
Rotations are a mess. Rotating now causes all the UICollectionView tiles to get missized (and the embedded images end up different sizes to each other for some reason). Have blocked rotations and fixed orientation to portrait until this can be resolved.

**Comment by tudormunteanu** [comment]
Did you take a look a project I forked from kidzvids2?

**Comment by bobbyali** [comment]
Yup, looked at that already. Looks like you've figured out the bug for why
the view doesn't go into Portrait Upside Down. I'll incorporate that into
my code later.

The orientation issues I'm having now are completely different... the
collection view icons get totally messed up now when I rotate the display.
I've commented out all the rotation code for now until I can figure it out.

**Comment by bobbyali** [comment]
Fixed using this post:

http://stackoverflow.com/questions/12412240/ios-bounds-change-after-rotating-to-landscape-then-back-to-portrait

The rotation update instructions needed to go in a specific method ('layoutSubviews').
