### ISSUE TITLE
Instructions page

### ISSUE THREAD

**Issue by bobbyali** [bobbyali/kidzvids2#27]
What's the best way of adding an instructions page? I'm thinking of having a startup screen which appears before the GridVC which tells parents how to use the app. Does this need a separate view controller, or is there a simpler way of doing it? 

Also I'm thinking that I may need two different layouts of the info page, for iPhones and iPads. Any suggestions on how to do this?

**Comment by tudormunteanu** [comment]
This sounds like the perfect use case for https://www.cocoacontrols.com/controls/eaintroview
